# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "supertpx"
repo_name: "arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/arxiv-daily.json'

md_readme_path: 'README.md'


keywords:
    "agent":
        filters: [LLM agent,Multi-Agent]
    "llm":
        filters: ["Large Language Model"]
    "infer":
        filters: ["LLM inference"]
    "train":
        filters: ["LLM Train"]
